services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: $UID:$GID
    ports: 
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: $UID:$GID
    ports:
      - "3010:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus